name: Run Utility Bot

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "utilitybot.py"
  schedule:
    - cron: "13 * * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  activate:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[no-update]') }}
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3.5.3 # checkout the repository content

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: Install required Python packages
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Activate Utility Bot # run utilitybot.py
        run: python3 utilitybot.py ${{ secrets.BOT_EMAIL }} ${{ secrets.BOT_PASSWORD }}
