name: run utilitybot.py

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: execute py script # run utilitybot.py
        run: python3 utilitybot.py ${{ secrets.BOT_EMAIL }} ${{ secrets.BOT_PASSWORD }}
