name: Post event into chat room

on: [branch_protection_rule, create, delete, deployment, deployment_status, discussion, discussion_comment, fork, gollum, issue_comment, issues, label, merge_group, milestone, page_build, project, project_card, project_column, public, pull_request, pull_request_review, pull_request_review_comment, pull_request_target, push, registry_package, release, repository_dispatch, schedule, watch]

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Send Message
        run: python3 sendmsg.py
        env:
          email: ${{ secrets.BOT_EMAIL }}
          password: ${{ secrets.BOT_PASSWORD }}
          event: ${{ github.event_name }}
          actor: ${{ github.actor }}
          payload: ${{ toJSON(github.event) }}
